data_params:
  path_answer: ./data/nlpcc_dataset/testset_answer.txt
  path_result: ./data/nlpcc_dataset/test_result.result
  path_test: ./data/nlpcc_dataset/testset.txt
  path_train: ./data/nlpcc_dataset/trainset.txt
  sep: table
  voc_params:
    char: {min_count: 0, path: ./Res/voc/char.voc.pkl}
    f1: {min_count: 0, path: ./Res/voc/f1.voc.pkl}
    f2: {min_count: 0, path: ./Res/voc/f2.voc.pkl}
    label: {min_count: 0, path: ./Res/voc/label.voc.pkl}
model: NER
model_params:
  batch_size: 64
  bilstm_params: {num_layers: 4, num_units: 256, rnn_dropout: 0.2}
  clip: 10
  conv_dropout: 0.2
  conv_filter_len_list: [1, 2, 3, 4, 5]
  conv_filter_size_list: [8, 8, 8, 8, 8]
  dev_size: 0.2
  dropout_rate: 0.5
  embed_params:
    char:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [3835, 16]
    f1:
      dropout_rate: 0.3
      path: ./Res/embed/char_embed.pkl
      path_pre_train: ./data/embedding/nlpcc_embed_d200_w9_all
      shape: [3839, 200]
    f2:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [5, 32]
  feature_names: [f1]
  l2_rate: 0.001
  learning_rate: 0.002
  max_patience: 5
  nb_classes: 123
  nb_epoch: 200
  path_model: ./Model/nlpcc-d200-w9-l4-bilstm-crf/best_model
  rnn_unit: lstm
  sequence_len_pt: 98
  sequence_length: 84
  use_char_feature: false
  use_crf: true
  word_len_pt: 95
  word_length: 1
